import PDFDocument from 'pdfkit-table';

/**
 * Generate PDF for Audit Trail
 * @param {Array} logs - The fetched audit logs
 * @param {Object} user - The user who generated the report
 * @param {Object} filters - Applied filters for metadata
 * @param {WritableStream} responseStream - The Express res object to pipe the PDF to
 */
export const generateAuditPdfStream = (logs, user, filters, responseStream) => {
  return new Promise((resolve, reject) => {
    try {
      // Create a document
      const doc = new PDFDocument({ margin: 30, size: 'A4', layout: 'landscape' });

      // Pipe its output to the Express response
      doc.pipe(responseStream);

      // Handle stream events
      responseStream.on('finish', () => resolve());
      responseStream.on('error', (err) => reject(err));
      doc.on('error', (err) => reject(err));

      // --- HEADER ---
      doc.fontSize(20).font('Helvetica-Bold').fillColor('#1E293B')
         .text('SVS Furniture Works', { align: 'center' });
      
      doc.fontSize(14).font('Helvetica').fillColor('#334155')
         .text('Audit Trail Report', { align: 'center' });
      doc.moveDown();

      // --- METADATA ---
      doc.fontSize(10).fillColor('#64748B');
      doc.text(`Generated Date: ${new Date().toLocaleString()}`);
      doc.text(`Generated By: ${user?.fullName || 'System User'}`);
      
      const filterStrings = [];
      if (filters?.module) filterStrings.push(`Module: ${filters.module}`);
      if (filters?.action) filterStrings.push(`Action: ${filters.action}`);
      if (filters?.startDate) filterStrings.push(`From: ${new Date(filters.startDate).toLocaleDateString()}`);
      if (filters?.endDate) filterStrings.push(`To: ${new Date(filters.endDate).toLocaleDateString()}`);
      
      if (filterStrings.length > 0) {
        doc.text(`Active Filters: ${filterStrings.join(' | ')}`);
      } else {
        doc.text(`Active Filters: None`);
      }
      doc.moveDown();

      // --- TABLE ---
      const table = {
        title: "Audit Logs",
        headers: [
          { label: "Date & Time", property: 'date', width: 100 },
          { label: "User", property: 'user', width: 100 },
          { label: "Action", property: 'action', width: 80 },
          { label: "Module", property: 'module', width: 80 },
          { label: "Details", property: 'details', width: 350 }
        ],
        datas: logs.map(l => ({
          date: new Date(l.createdAt).toLocaleString(),
          user: l.user?.fullName || 'System',
          action: l.action,
          module: l.module,
          details: `IP: ${l.ipAddress || 'N/A'}, Browser: ${l.browser || 'N/A'} - ${l.details || ''}`
        }))
      };

      doc.table(table, {
        prepareHeader: () => doc.font("Helvetica-Bold").fontSize(10).fillColor('#FFFFFF'),
        prepareRow: (row, indexColumn, indexRow, rectRow, rectCell) => {
          doc.font("Helvetica").fontSize(9).fillColor('#334155');
        },
        columnsSize: [110, 110, 90, 90, 360],
        divider: {
          header: { disabled: false, width: 2, opacity: 1, color: '#3B82F6' },
          horizontal: { disabled: false, width: 1, opacity: 0.3, color: '#CBD5E1' }
        },
        padding: 5
      });

      // --- FOOTER ---
      // Add page numbers at the bottom of every page
      const pages = doc.bufferedPageRange();
      for (let i = 0; i < pages.count; i++) {
        doc.switchToPage(i);
        doc.fontSize(8).fillColor('#94A3B8');
        doc.text(
          `Page ${i + 1} of ${pages.count}  |  Generated by SVS Furniture ERP`,
          50,
          doc.page.height - 40,
          { align: 'center', width: doc.page.width - 100 }
        );
      }

      // Finalize PDF file
      doc.end();
    } catch (error) {
      reject(error);
    }
  });
};
