export const PERMISSIONS = {
  Admin: {
    dashboard:           'full',
    customers:           'full',
    orders:              'full',
    specificationSheets: 'full',
    inventory:           'full',
    production:          'full',
    delivery:            'full',
    reports:             'full',
    alerts:              'full',
    userManagement:      'full',
  },
  Management: {
    dashboard:           'view',
    customers:           'view',
    orders:              'view',
    specificationSheets: 'none',
    inventory:           'view',
    production:          'view',
    delivery:            'view',
    reports:             'full',
    alerts:              'view',
    userManagement:      'none',
  },
  'Sales Staff': {
    dashboard:           'view',
    customers:           'full',
    orders:              'full',
    specificationSheets: 'full',
    inventory:           'none',
    production:          'none',
    delivery:            'none',
    reports:             'none',
    alerts:              'view',
    userManagement:      'none',
  },
  'Production Staff': {
    dashboard:           'none',
    customers:           'none',
    orders:              'view',
    specificationSheets: 'view',
    inventory:           'none',
    production:          'view',
    delivery:            'none',
    reports:             'none',
    alerts:              'view',
    userManagement:      'none',
  },
  'Delivery Staff': {
    dashboard:           'none',
    customers:           'none',
    orders:              'view',
    specificationSheets: 'none',
    inventory:           'none',
    production:          'none',
    delivery:            'view',
    reports:             'none',
    alerts:              'view',
    userManagement:      'none',
  },
};
